### ISSUE TITLE
TypeError: importhe/application.py

### ISSUE THREAD

**Issue by schoeller** [hoettges/QKan-plugin-HE7#13]
An error is thrown while importing:

```
An error has occurred while executing Python code: 

TypeError: expected str, bytes or os.PathLike object, not tuple 
Traceback (most recent call last):
  File "C:/Users/sschoeller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qkan_he7\importhe\application.py", line 270, in selectFile_HeErgDB
    if os.path.dirname(filename) != '':
  File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\ntpath.py", line 221, in dirname
    return split(p)[0]
  File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not tuple


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.10-Madeira Madeira, 3d97aaae88
```

**Comment by Invisi** [comment]
Thanks for the reports and the PRs, I'll take a look at the other ones in the next few days.
